# Generated by Django 5.2.4 on 2025-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunLogTable',
            fields=[
                ('ray_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Aborted', 'Aborted'), ('Running', 'Running')], max_length=20)),
            ],
        ),
    ]
